version: '2'
services:
   client-demo:
      container_name: client-demo
      build:
         context: client-demo
         dockerfile: Dockerfile
      image: client-demo:latest
      ports:
      - 8080:8080
      networks:
      - spring-network
   postgres:
      image: postgres:10.5
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      ports:
      - 5432:5432
      networks:
      - spring-network
networks:
   spring-network:
      driver: bridge